import json

translations = {
    "tr": {
        "rankNovice": "Acemi",
        "rankApprentice": "Çırak",
        "rankJourneyman": "Kalfa",
        "rankMaster": "Usta Tamirci",
        "tip1": "İpucu: Önce müşteriyi dinle, sonra gözle. Teşhis koymadan tamir yapma!",
        "tip2": "İpucu: OBD-II tarayıcı her zaman en iyi dostundur. İlk iş olarak bağla.",
        "tip3": "İpucu: Eğer motor dönüyor ama çalışmıyorsa, ateşleme veya yakıt sorunu olabilir.",
        "tip4": "İpucu: İpuçları tükenirse ustadan yardım isteyebilirsin. Pro pakette sınırsızdır.",
        "tip5": "İpucu: Ucuz parçaları önce test et. Rastgele parça değiştirmek sana eksi puan getirir.",
        "tip6": "İpucu: Fren sesleri genelde balatalardan gelir, ancak kampanaları da kontrol etmeyi unutma.",
        "paywallTitle": "PRO TAMİRCİ",
        "paywallHero": "Garajın Yeni Patronu Ol!",
        "paywallFeature1": "Sınırsız Enerji (Beklemek yok)",
        "paywallFeature2": "Her vaka için sınırsız ipucu",
        "paywallFeature3": "Tüm Reklamları Kaldır",
        "weeklyPlan": "Haftalık Plan",
        "weeklyPlanSub": "Kısa süreli ustalık",
        "monthlyPlan": "Aylık Plan",
        "monthlyPlanSub": "Sadece 13 ₺ / Gün",
        "monthlyPlanTag": "EN ÇOK SATAN — %61 KÂR",
        "yearlyPlan": "Yıllık Plan",
        "yearlyPlanSub": "Uzun vadeli yatırım",
        "upgradeNow": "ŞİMDİ YÜKSELT",
        "termsOfUse": "Kullanım Koşulları",
        "privacyPolicy": "Gizlilik Politikası",
        "restore": "Geri Yükle",
        "paywallSuccess": "Satın alma başarılı! Pro özellikler açıldı.",
        "case1Vehicle": "2002 Japon Sedan 1.6",
        "case1Complaint": "Araba hiç çalışmıyor, anahtar çevirince ses yok.",
        "case2Vehicle": "2006 Amerikan Hatchback 1.6",
        "case2Complaint": "Anahtar çevirince tıklama sesi var ama motor dönmüyor.",
        "case3Vehicle": "2008 Alman Hatchback 1.4",
        "case3Complaint": "Sol far çalışmıyor, sağ far sorunsuz.",
        "case4Vehicle": "2010 Fransız Sedan 1.5",
        "case4Complaint": "Silecekler hiç hareket etmiyor, cam suyu fışkırıyor.",
        "case5Vehicle": "2004 Alman Hatchback 1.6",
        "case5Complaint": "Klima hava üflüyor ama hiç soğutmuyor.",
        "case6Vehicle": "2015 Kore Hatchback 1.4",
        "case6Complaint": "Motor harareti 15 dakikada kırmızıya çıkıyor.",
        "case7Vehicle": "1998 İtalyan Hatchback 1.6",
        "case7Complaint": "Sabahları zor çalışıyor, rölantide sallanıyor.",
        "case8Vehicle": "2012 Japon Sedan 1.6",
        "case8Complaint": "Vites geçişleri, özellikle 1-2 arası çok sert ve sarsıntılı.",
        "case9Vehicle": "2009 Fransız Hatchback 1.4",
        "case9Complaint": "Düşük hızda frene basınca ön tekerlerden tiz bir gıcırtı geliyor.",
        "case10Vehicle": "2007 Japon Hatchback 1.5",
        "case10Complaint": "Gaza basınca devir artıyor ama araç hızlanmıyor (bağırıyor ama gitmiyor).",
        "case11Vehicle": "2005 Premium Alman Sedan 2.0",
        "case11Complaint": "Motor uyarı lambası yanıyor ve araç 3000 deviri geçmiyor.",
        "case12Vehicle": "2011 Premium Alman Sedan 2.1",
        "case12Complaint": "Motor suyuna yağ karışmış, antifriz kabı tahin gibi olmuş.",
        "case13Vehicle": "2003 Premium Alman Sedan 1.8",
        "case13Complaint": "Ön camdan ve sunroof çevresinden yağmurlu havalarda su alıyor.",
        "case14Vehicle": "2014 Premium İsveç Sedan 2.0",
        "case14Complaint": "Direksiyon çok ağırlaştı, döndürmek neredeyse imkansız.",
        "case15Vehicle": "2016 Çek Sedan 1.6",
        "case15Complaint": "Hız sabitleyici ve şerit takip asistanı devre dışı kaldı uyarısı."
    },
    "en": {
        "rankNovice": "Novice",
        "rankApprentice": "Apprentice",
        "rankJourneyman": "Journeyman",
        "rankMaster": "Master Mechanic",
        "tip1": "Tip: Listen to the customer first, then observe. Don't repair without a diagnosis!",
        "tip2": "Tip: The OBD-II scanner is your best friend. Always plug it in first.",
        "tip3": "Tip: If the engine cranks but won't start, it might be an ignition or fuel issue.",
        "tip4": "Tip: If you run out of hints, ask the Master. Pro users have unlimited hints.",
        "tip5": "Tip: Test cheap parts first. Guessing parts will cost you reputation points.",
        "tip6": "Tip: Brake noises usually come from pads, but don't forget to check the drums.",
        "paywallTitle": "PRO MECHANIC",
        "paywallHero": "Become the Boss of the Garage!",
        "paywallFeature1": "Unlimited Energy (No waiting)",
        "paywallFeature2": "Unlimited hints for every case",
        "paywallFeature3": "Remove All Ads",
        "weeklyPlan": "Weekly Plan",
        "weeklyPlanSub": "Short-term mastery",
        "monthlyPlan": "Monthly Plan",
        "monthlyPlanSub": "Only $0.50 / Day",
        "monthlyPlanTag": "BEST SELLER — 61% OFF",
        "yearlyPlan": "Yearly Plan",
        "yearlyPlanSub": "Long-term investment",
        "upgradeNow": "UPGRADE NOW",
        "termsOfUse": "Terms of Use",
        "privacyPolicy": "Privacy Policy",
        "restore": "Restore",
        "paywallSuccess": "Purchase successful! Pro features unlocked.",
        "case1Vehicle": "2002 Japanese Sedan 1.6",
        "case1Complaint": "Car doesn't start at all, no sound when turning the key.",
        "case2Vehicle": "2006 American Hatchback 1.6",
        "case2Complaint": "Clicking sound when turning key but engine won't crank.",
        "case3Vehicle": "2008 German Hatchback 1.4",
        "case3Complaint": "Left headlight doesn't work, right is fine.",
        "case4Vehicle": "2010 French Sedan 1.5",
        "case4Complaint": "Wipers not moving at all, but washer fluid sprays.",
        "case5Vehicle": "2004 German Hatchback 1.6",
        "case5Complaint": "A/C blows air but it's not cold at all.",
        "case6Vehicle": "2015 Korean Hatchback 1.4",
        "case6Complaint": "Engine temperature hits the red zone in 15 minutes.",
        "case7Vehicle": "1998 Italian Hatchback 1.6",
        "case7Complaint": "Hard to start in mornings, shakes wildly at idle.",
        "case8Vehicle": "2012 Japanese Sedan 1.6",
        "case8Complaint": "Gear shifts, especially 1st to 2nd, are very rough.",
        "case9Vehicle": "2009 French Hatchback 1.4",
        "case9Complaint": "High-pitched squeak from front wheels when braking at low speed.",
        "case10Vehicle": "2007 Japanese Hatchback 1.5",
        "case10Complaint": "RPM goes up when stepping on gas but car barely accelerates.",
        "case11Vehicle": "2005 Premium German Sedan 2.0",
        "case11Complaint": "Check engine light is on and car won't go past 3000 RPM.",
        "case12Vehicle": "2011 Premium German Sedan 2.1",
        "case12Complaint": "Oil mixed with coolant, expansion tank looks like a milkshake.",
        "case13Vehicle": "2003 Premium German Sedan 1.8",
        "case13Complaint": "Water leaking inside from the windshield and sunroof in the rain.",
        "case14Vehicle": "2014 Premium Swedish Sedan 2.0",
        "case14Complaint": "Steering wheel got super heavy, almost impossible to turn.",
        "case15Vehicle": "2016 Czech Sedan 1.6",
        "case15Complaint": "Cruise control and lane assist disabled warnings on dash."
    },
    "ru": {
        "rankNovice": "Новичок",
        "rankApprentice": "Подмастерье",
        "rankJourneyman": "Опытный",
        "rankMaster": "Мастер",
        "tip1": "Совет: Сначала выслушайте клиента, затем осмотрите. Не чините без диагностики!",
        "tip2": "Совет: Сканер OBD-II — ваш лучший друг. Всегда подключайте его первым.",
        "tip3": "Совет: Если стартер крутит, но двигатель не заводится — проблема в зажигании или топливе.",
        "tip4": "Совет: Закончились подсказки? Спросите Мастера. В Pro-версии подсказки безлимитны.",
        "tip5": "Совет: Сначала проверяйте дешевые детали. Замена наугад снизит вашу репутацию.",
        "tip6": "Совет: Скрип тормозов обычно идет от колодок, но не забывайте проверять барабаны.",
        "paywallTitle": "PRO МЕХАНИК",
        "paywallHero": "Стань Боссом Гаража!",
        "paywallFeature1": "Безлимитная энергия (Без ожиданий)",
        "paywallFeature2": "Безлимитные подсказки для всех дел",
        "paywallFeature3": "Отключение всей рекламы",
        "weeklyPlan": "План на неделю",
        "weeklyPlanSub": "Краткосрочное мастерство",
        "monthlyPlan": "План на месяц",
        "monthlyPlanSub": "Всего 40 ₽ / день",
        "monthlyPlanTag": "ХИТ ПРОДАЖ — ВЫГОДА 61%",
        "yearlyPlan": "План на год",
        "yearlyPlanSub": "Долгосрочная инвестиция",
        "upgradeNow": "УЛУЧШИТЬ СЕЙЧАС",
        "termsOfUse": "Условия использования",
        "privacyPolicy": "Политика конфиденциальности",
        "restore": "Восстановить",
        "paywallSuccess": "Покупка успешна! Pro функции разблокированы.",
        "case1Vehicle": "2002 Японский седан 1.6",
        "case1Complaint": "Машина вообще не заводится, при повороте ключа нет звука.",
        "case2Vehicle": "2006 Американский хэтчбек 1.6",
        "case2Complaint": "Щелчки при повороте ключа, но двигатель не крутит.",
        "case3Vehicle": "2008 Немецкий хэтчбек 1.4",
        "case3Complaint": "Левая фара не работает, правая в порядке.",
        "case4Vehicle": "2010 Французский седан 1.5",
        "case4Complaint": "Дворники не двигаются, но омывайка брызгает.",
        "case5Vehicle": "2004 Немецкий хэтчбек 1.6",
        "case5Complaint": "Кондиционер дует, но воздух совсем не холодный.",
        "case6Vehicle": "2015 Корейский хэтчбек 1.4",
        "case6Complaint": "Температура двигателя уходит в красную зону за 15 минут.",
        "case7Vehicle": "1998 Итальянский хэтчбек 1.6",
        "case7Complaint": "Трудно заводится по утрам, сильно трясется на холостых.",
        "case8Vehicle": "2012 Японский седан 1.6",
        "case8Complaint": "Переключение передач, особенно с 1 на 2, очень жесткое.",
        "case9Vehicle": "2009 Французский хэтчбек 1.4",
        "case9Complaint": "Пронзительный писк от передних колес при торможении на малой скорости.",
        "case10Vehicle": "2007 Японский хэтчбек 1.5",
        "case10Complaint": "Обороты растут при нажатии на газ, но машина почти не ускоряется.",
        "case11Vehicle": "2005 Премиальный немецкий седан 2.0",
        "case11Complaint": "Горит Check Engine, машина не набирает больше 3000 оборотов.",
        "case12Vehicle": "2011 Премиальный немецкий седан 2.1",
        "case12Complaint": "Масло смешалось с антифризом, в бачке эмульсия.",
        "case13Vehicle": "2003 Премиальный немецкий седан 1.8",
        "case13Complaint": "Во время дождя в салон протекает вода через лобовое стекло и люк.",
        "case14Vehicle": "2014 Премиальный шведский седан 2.0",
        "case14Complaint": "Руль стал очень тяжелым, повернуть почти невозможно.",
        "case15Vehicle": "2016 Чешский седан 1.6",
        "case15Complaint": "Ошибки на панели: круиз-контроль и удержание в полосе отключены."
    },
    "zh": {
        "rankNovice": "新手",
        "rankApprentice": "学徒",
        "rankJourneyman": "熟练工",
        "rankMaster": "大师",
        "tip1": "提示：先听取客户意见，再进行观察。在没有诊断之前不要随意修理！",
        "tip2": "提示：OBD-II 扫描仪是你最好的朋友。第一步永远是连接它。",
        "tip3": "提示：如果发动机能转动但无法启动，可能是点火或燃油问题。",
        "tip4": "提示：如果提示用完了，可以向大师求助。Pro 用户有无限提示。",
        "tip5": "提示：先测试便宜的零件。盲目更换零件会扣除声望点数。",
        "tip6": "提示：刹车异响通常来自刹车片，但别忘了检查刹车鼓。",
        "paywallTitle": "PRO 维修工",
        "paywallHero": "成为车库的新老板！",
        "paywallFeature1": "无限能量（无需等待）",
        "paywallFeature2": "每个案件都有无限提示",
        "paywallFeature3": "移除所有广告",
        "weeklyPlan": "周度计划",
        "weeklyPlanSub": "短期掌握",
        "monthlyPlan": "月度计划",
        "monthlyPlanSub": "每天只需 ¥3",
        "monthlyPlanTag": "最畅销 — 节省 61%",
        "yearlyPlan": "年度计划",
        "yearlyPlanSub": "长期投资",
        "upgradeNow": "立即升级",
        "termsOfUse": "使用条款",
        "privacyPolicy": "隐私政策",
        "restore": "恢复购买",
        "paywallSuccess": "购买成功！Pro 功能已解锁。",
        "case1Vehicle": "2002 日本轿车 1.6",
        "case1Complaint": "车完全无法启动，拧钥匙时没有任何声音。",
        "case2Vehicle": "2006 美国掀背车 1.6",
        "case2Complaint": "拧钥匙时有咔哒声，但发动机不转。",
        "case3Vehicle": "2008 德国掀背车 1.4",
        "case3Complaint": "左侧大灯不亮，右侧正常。",
        "case4Vehicle": "2010 法国轿车 1.5",
        "case4Complaint": "雨刮器完全不动，但玻璃水能喷出。",
        "case5Vehicle": "2004 德国掀背车 1.6",
        "case5Complaint": "空调出风但完全不冷。",
        "case6Vehicle": "2015 韩国掀背车 1.4",
        "case6Complaint": "发动机温度在 15 分钟内飙升到红区。",
        "case7Vehicle": "1998 意大利掀背车 1.6",
        "case7Complaint": "早晨启动困难，怠速时抖动剧烈。",
        "case8Vehicle": "2012 日本轿车 1.6",
        "case8Complaint": "换挡，尤其是 1 挡到 2 挡时，非常顿挫。",
        "case9Vehicle": "2009 法国掀背车 1.4",
        "case9Complaint": "低速刹车时前轮发出刺耳的尖叫声。",
        "case10Vehicle": "2007 日本掀背车 1.5",
        "case10Complaint": "踩油门时转速上升，但车几乎不加速。",
        "case11Vehicle": "2005 高级德国轿车 2.0",
        "case11Complaint": "发动机故障灯亮起，转速无法超过 3000 转。",
        "case12Vehicle": "2011 高级德国轿车 2.1",
        "case12Complaint": "机油和防冻液混合，膨胀水箱里像奶昔一样。",
        "case13Vehicle": "2003 高级德国轿车 1.8",
        "case13Complaint": "下雨时挡风玻璃和天窗周围漏水。",
        "case14Vehicle": "2014 高级瑞典轿车 2.0",
        "case14Complaint": "方向盘变得非常沉重，几乎无法转动。",
        "case15Vehicle": "2016 捷克轿车 1.6",
        "case15Complaint": "仪表盘显示定速巡航和车道保持辅助系统已禁用。"
    }
}

for lang in translations:
    filepath = f"c:/Proje/Sanayi Ustasu/app/lib/l10n/app_{lang}.arb"
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    for k, v in translations[lang].items():
        data[k] = v
        
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Added all keys successfully!")
